/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверить, что процесс API работает */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверить готовность API принимать трафик */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Служебный список демо-ссылок на заявки */
        get: operations["DemoLinksController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{accessSecret}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Кабинет одной заявки по секрету в URL */
        get: operations["RequestPortalController_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDataDto: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
        TraceMetaDto: {
            /** Format: uuid */
            traceId: string;
        };
        HealthResponseDto: {
            data: components["schemas"]["HealthDataDto"];
            meta: components["schemas"]["TraceMetaDto"];
        };
        DemoLinkItemDto: {
            /** @example З-10041 */
            publicNumber: string;
            /** @example ООО «Северэнергомонтаж» */
            counterpartyName: string;
            /** @example Щит ЩО-70 800 А */
            title: string;
            /**
             * @example accepted
             * @enum {string}
             */
            status: "accepted" | "in_calculation" | "quote_ready" | "invoice_issued";
            /** @example Принят */
            statusLabel: string;
            /** @example /r/seed-z10041-accepted-severenergo */
            portalPath: string;
            /**
             * Format: date-time
             * @example 2026-09-01T10:00:00.000Z
             */
            updatedAt: string;
        };
        DemoLinksDataDto: {
            items: components["schemas"]["DemoLinkItemDto"][];
        };
        DemoLinksResponseDto: {
            data: components["schemas"]["DemoLinksDataDto"];
            meta: components["schemas"]["TraceMetaDto"];
        };
        RequestStageDto: {
            /** @enum {string} */
            status: "accepted" | "in_calculation" | "quote_ready" | "invoice_issued";
            /** @example Принят */
            label: string;
            /**
             * Format: date-time
             * @example 2026-09-01T09:00:00.000Z
             */
            reachedAt: string | null;
        };
        RequestSpecLineDto: {
            name: string;
            /**
             * Format: int32
             * @example 1
             */
            quantity: number;
            /** @example шт */
            unit: string;
            /** @example IP54, навесное */
            comment?: string;
        };
        RequestFileDto: {
            /** @example КП-З-10043.pdf */
            fileName: string;
            /** @enum {string} */
            kind: "questionnaire" | "quote" | "invoice";
            /**
             * Format: int32
             * @example 240000
             */
            byteSize: number;
            /**
             * Format: date-time
             * @example 2026-09-04T12:00:00.000Z
             */
            uploadedAt: string;
        };
        RequestPortalDataDto: {
            /** @example З-10043 */
            publicNumber: string;
            /** @example ИП Кузнецов П.А. */
            counterpartyName: string;
            /** @example ВРУ 400 А */
            title: string;
            /**
             * @example quote_ready
             * @enum {string}
             */
            status: "accepted" | "in_calculation" | "quote_ready" | "invoice_issued";
            /** @example КП готово */
            statusLabel: string;
            /**
             * Format: date-time
             * @example 2026-09-04T12:00:00.000Z
             */
            updatedAt: string;
            /** @example ПК «Нордщит» */
            plantName: string;
            stages: components["schemas"]["RequestStageDto"][];
            specLines: components["schemas"]["RequestSpecLineDto"][];
            files: components["schemas"]["RequestFileDto"][];
            /** @example true */
            demoLive?: boolean;
        };
        RequestPortalResponseDto: {
            data: components["schemas"]["RequestPortalDataDto"];
            meta: components["schemas"]["TraceMetaDto"];
        };
        ProblemDetailsDto: {
            /** @example One or more fields are invalid */
            detail: string;
            /**
             * @example [
             *       {
             *         "field": "pageSize",
             *         "message": "pageSize must not be greater than 48"
             *       }
             *     ]
             */
            errors?: {
                field: string;
                message: string;
            }[];
            /** @example /api/v1/resources */
            instance: string;
            /** @example 400 */
            status: number;
            /** @example Validation failed */
            title: string;
            /** Format: uuid */
            traceId: string;
            /** @example https://demo.local/problems/validation-error */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Процесс жив */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API принимает трафик */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
            /** @description API ещё не слушает, уже останавливается или база данных недоступна */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    DemoLinksController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoLinksResponseDto"];
                };
            };
        };
    };
    RequestPortalController_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accessSecret: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPortalResponseDto"];
                };
            };
            /** @description Заявка не найдена по секрету */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Слишком много запросов с этого IP */
            429: {
                headers: {
                    /** @description Seconds until the request may be retried */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
}
